#!/bin/bash -x

#commandes fire wall 

#sudo iptables -P FORWARD DROP



#nat

sudo iptables -t nat -A POSTROUTING -s 10.10.10.0/24  -j MASQUERADE

sudo iptables -t nat -A PREROUTING -p tcp --dport 53 -j DNAT --to 8.8.4.4:53
sudo iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT --to 8.8.4.4:53

sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8080